In [1]:
%pip install seaborn

Requirement already satisfied: seaborn in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from seaborn) (2.5.1)
Requirement already satisfied: pandas>=1.2 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=9 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install matplotlib

Requirement already satisfied: matplotlib in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.25 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from matplotlib) (2.5.1)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=9 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install yfinance

Requirement already satisfied: yfinance in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (1.5.1)
Requirement already satisfied: pandas>=1.3.0 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from yfinance) (3.0.5)
Requirement already satisfied: numpy>=1.16.5 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from yfinance) (2.5.1)
Requirement already satisfied: requests>=2.31 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from yfinance) (2.34.2)
Requirement already satisfied: multitasking>=0.0.7 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from yfinance) (4.11.0)
Requirement already satisfied: pytz>=2022.5 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from yfinance) (2026.2)
Requirement already satisfied: peewee>=3.16.2 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from yfinance) (4.2.6)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from yfinance) (4.15.0)
Requirement already satisfied: curl_cffi>=0.15 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from yfinance) (7.35.1)
Requirement already satisfied: websockets>=13.0 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from yfinance) (16.1.1)
Requirement already satisfied: soupsieve>=1.6.1 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.9.1)
Requirement already satisfied: typing-extensions>=4.0.0 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Requirement already satisfied: cffi>=2.0.0 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2.1.0)
Requirement already satisfied: certifi>=2024.2.2 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2026.7.22)
Requirement already satisfied: rich in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (15.0.0)
Requirement already satisfied: pycparser in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.7.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from rich->curl_cffi>=0.15->yfinance) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/envs/FINANCE_AI_AGENT/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [12]:
#Libraries 
import yfinance as yf
import matplotlib.pyplot as plt 
import seaborn as sns
from matplotlib import rcParams
from matplotlib.ticker import PercentFormatter 

#Download data from yahoo finance
Tickers = ["AAPL", "MSFT"]

data = yf.download(
    Tickers,
    start='2022-01-01',
    end='2026-01-01'
)

prices = data["Close"]

[*********************100%***********************]  2 of 2 completed

In [13]:
prices

Ticker            AAPL        MSFT
Date
2022-01-03  177.939697  322.462372
2022-01-04  175.681381  316.933075
2022-01-05  171.008286  304.766693
2022-01-06  168.153549  302.358429
2022-01-07  168.319794  302.512634
...                ...         ...
2025-12-24  273.302216  485.856323
2025-12-26  272.893005  485.547699
2025-12-29  273.252350  484.940430
2025-12-30  272.573547  485.318726
2025-12-31  271.355835  481.475861

[1003 rows x 2 columns]

In [14]:
prices.head()

Ticker            AAPL        MSFT
Date
2022-01-03  177.939697  322.462372
2022-01-04  175.681381  316.933075
2022-01-05  171.008286  304.766693
2022-01-06  168.153549  302.358429
2022-01-07  168.319794  302.512634

In [15]:
prices.describe()

Ticker         AAPL         MSFT
count   1003.000000  1003.000000
mean     189.695471   360.387400
std       37.459387    88.031126
min      122.933548   207.733963
25%      161.893333   278.209579
50%      182.731567   367.548706
75%      220.545494   421.283813
max      285.659271   538.658508

In [16]:
prices.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1003 entries, 2022-01-03 to 2025-12-31
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AAPL    1003 non-null   float64
 1   MSFT    1003 non-null   float64
dtypes: float64(2)
memory usage: 23.5 KB